# Generated by Django 5.2.6 on 2025-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_anomaly', '0001_initial'),
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='users.device'),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='escalated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='feedback_provided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='parent_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_models', to='ai_anomaly.anomalydetectionmodel'),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='detected_by_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ai_anomaly.anomalydetectionmodel'),
        ),
        migrations.AddField(
            model_name='behavioralprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelperformancemetrics',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='ai_anomaly.anomalydetectionmodel'),
        ),
        migrations.AddField(
            model_name='threatintelligence',
            name='related_alerts',
            field=models.ManyToManyField(blank=True, related_name='related_intelligence', to='ai_anomaly.anomalyalert'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionmodel',
            index=models.Index(fields=['model_type', 'status'], name='anomaly_det_model_t_4d6b99_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionmodel',
            index=models.Index(fields=['is_active', 'deployment_priority'], name='anomaly_det_is_acti_465455_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionmodel',
            index=models.Index(fields=['version'], name='anomaly_det_version_5f5f26_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['alert_type', 'severity'], name='anomaly_ale_alert_t_0b8425_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['status', 'detected_at'], name='anomaly_ale_status_62765c_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['assigned_to', 'status'], name='anomaly_ale_assigne_c8e843_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['detected_by_model', 'detected_at'], name='anomaly_ale_detecte_b372be_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['affects_mission_critical', 'severity'], name='anomaly_ale_affects_59f24e_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralprofile',
            index=models.Index(fields=['user', 'is_active'], name='behavioral__user_id_513d01_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralprofile',
            index=models.Index(fields=['profile_start_date', 'profile_end_date'], name='behavioral__profile_0e6ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='behavioralprofile',
            index=models.Index(fields=['significant_drift_detected'], name='behavioral__signifi_055938_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformancemetrics',
            index=models.Index(fields=['model', 'measurement_date'], name='model_perfo_model_i_da5ef9_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformancemetrics',
            index=models.Index(fields=['drift_detected'], name='model_perfo_drift_d_977c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='modelperformancemetrics',
            index=models.Index(fields=['needs_retraining', 'retraining_priority'], name='model_perfo_needs_r_ab80cf_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelligence',
            index=models.Index(fields=['intel_type', 'is_active'], name='threat_inte_intel_t_87f16a_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelligence',
            index=models.Index(fields=['threat_level', 'confidence_level'], name='threat_inte_threat__ae3b37_idx'),
        ),
        migrations.AddIndex(
            model_name='threatintelligence',
            index=models.Index(fields=['expires_at'], name='threat_inte_expires_68e030_idx'),
        ),
    ]
