# Generated by Django 5.2.6 on 2025-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blockchain', '0001_initial'),
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.device'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.message'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blockchainsyncstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_sync_status', to='users.device'),
        ),
        migrations.AddField(
            model_name='localledgerblock',
            name='created_by_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blocks', to='users.device'),
        ),
        migrations.AddField(
            model_name='blockchaintransaction',
            name='local_block',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_tx', to='blockchain.localledgerblock'),
        ),
        migrations.AddField(
            model_name='messagetransaction',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blockchain.localledgerblock'),
        ),
        migrations.AddField(
            model_name='messagetransaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagetransaction',
            name='recipients',
            field=models.ManyToManyField(related_name='received_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetransaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetransaction',
            name='sender_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='users.device'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockchain.messagetransaction'),
        ),
        migrations.AddIndex(
            model_name='localledgerblock',
            index=models.Index(fields=['block_number'], name='local_ledge_block_n_4f2627_idx'),
        ),
        migrations.AddIndex(
            model_name='localledgerblock',
            index=models.Index(fields=['sync_status'], name='local_ledge_sync_st_ff7223_idx'),
        ),
        migrations.AddIndex(
            model_name='localledgerblock',
            index=models.Index(fields=['created_by_device', 'timestamp'], name='local_ledge_created_e0425d_idx'),
        ),
        migrations.AddIndex(
            model_name='localledgerblock',
            index=models.Index(fields=['blockchain_tx_hash'], name='local_ledge_blockch_de7a10_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['transaction_hash'], name='blockchain__transac_9bd57a_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['status', 'submitted_at'], name='blockchain__status_2fc7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['blockchain_network', 'block_number'], name='blockchain__blockch_598acb_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchaintransaction',
            index=models.Index(fields=['from_address'], name='blockchain__from_ad_5c42fe_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetransaction',
            index=models.Index(fields=['message', 'transaction_type'], name='message_tra_message_0d44eb_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetransaction',
            index=models.Index(fields=['sender', 'created_at'], name='message_tra_sender__037588_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetransaction',
            index=models.Index(fields=['block', 'transaction_index'], name='message_tra_block_i_d1298a_idx'),
        ),
        migrations.AddIndex(
            model_name='messagetransaction',
            index=models.Index(fields=['transaction_hash'], name='message_tra_transac_e0d462_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['device', 'timestamp'], name='audit_logs_device__3e756c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['log_type', 'timestamp'], name='audit_logs_log_typ_e5ee4b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['blockchain_anchored'], name='audit_logs_blockch_1b7375_idx'),
        ),
    ]
