# Generated by Django 5.2.6 on 2025-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_widgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missionreport',
            name='mission_commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commanded_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_metrics', to='users.device'),
        ),
        migrations.AddField(
            model_name='useractivitysummary',
            name='primary_device_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_usage_summaries', to='users.device'),
        ),
        migrations.AddField(
            model_name='useractivitysummary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['widget_type', 'is_active'], name='dashboard_w_widget__fe02c1_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['created_by', 'is_shared'], name='dashboard_w_created_77d64f_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['dashboard_row', 'dashboard_column'], name='dashboard_w_dashboa_6cd104_idx'),
        ),
        migrations.AddIndex(
            model_name='missionreport',
            index=models.Index(fields=['mission_commander', 'mission_status'], name='mission_rep_mission_b404fd_idx'),
        ),
        migrations.AddIndex(
            model_name='missionreport',
            index=models.Index(fields=['mission_start_time', 'mission_end_time'], name='mission_rep_mission_f5267b_idx'),
        ),
        migrations.AddIndex(
            model_name='missionreport',
            index=models.Index(fields=['classification_level'], name='mission_rep_classif_4ea06c_idx'),
        ),
        migrations.AddIndex(
            model_name='missionreport',
            index=models.Index(fields=['generated_at'], name='mission_rep_generat_f3cce0_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['category', 'metric_name', 'timestamp'], name='system_metr_categor_873342_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['device', 'timestamp'], name='system_metr_device__0ad9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='systemmetrics',
            index=models.Index(fields=['alert_triggered'], name='system_metr_alert_t_13e585_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitysummary',
            index=models.Index(fields=['user', 'period_start'], name='user_activi_user_id_822ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitysummary',
            index=models.Index(fields=['anomalous_behavior_detected'], name='user_activi_anomalo_992c73_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitysummary',
            index=models.Index(fields=['period_type', 'generated_at'], name='user_activi_period__4077d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useractivitysummary',
            unique_together={('user', 'period_type', 'period_start')},
        ),
    ]
