# Generated by Django 5.2.6 on 2025-09-13 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0002_initial'),
        ('p2p_sync', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinemessagequeue',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_message_queue', to='users.device'),
        ),
        migrations.AddField(
            model_name='offlinemessagequeue',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_entries', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='p2psyncstatus',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_sync_status', to='users.device'),
        ),
        migrations.AddField(
            model_name='peerconnection',
            name='local_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='users.device'),
        ),
        migrations.AddField(
            model_name='peerconnection',
            name='remote_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='users.device'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='affected_devices',
            field=models.ManyToManyField(related_name='sync_conflicts', to='users.device'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='assigned_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='local_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_conflicts', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='syncconflict',
            name='remote_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_conflicts', to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='offlinemessagequeue',
            index=models.Index(fields=['device', 'status'], name='offline_mes_device__0ee573_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinemessagequeue',
            index=models.Index(fields=['priority', 'queued_at'], name='offline_mes_priorit_9fb5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinemessagequeue',
            index=models.Index(fields=['next_sync_attempt_at'], name='offline_mes_next_sy_89057c_idx'),
        ),
        migrations.AddIndex(
            model_name='offlinemessagequeue',
            index=models.Index(fields=['has_conflict'], name='offline_mes_has_con_3dcb82_idx'),
        ),
        migrations.AddIndex(
            model_name='peerconnection',
            index=models.Index(fields=['local_device', 'status'], name='peer_connec_local_d_1d5b7e_idx'),
        ),
        migrations.AddIndex(
            model_name='peerconnection',
            index=models.Index(fields=['security_level', 'trust_score'], name='peer_connec_securit_fd5783_idx'),
        ),
        migrations.AddIndex(
            model_name='peerconnection',
            index=models.Index(fields=['connection_type', 'status'], name='peer_connec_connect_89091f_idx'),
        ),
        migrations.AddIndex(
            model_name='peerconnection',
            index=models.Index(fields=['last_seen_at'], name='peer_connec_last_se_46db96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerconnection',
            unique_together={('local_device', 'remote_device')},
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['conflict_type', 'resolution_status'], name='sync_confli_conflic_fc3a04_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['assigned_reviewer', 'resolution_status'], name='sync_confli_assigne_3e30ad_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['affects_mission_critical', 'detected_at'], name='sync_confli_affects_c10b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='syncconflict',
            index=models.Index(fields=['review_deadline'], name='sync_confli_review__df2d83_idx'),
        ),
    ]
