# Generated by Django 5.2.6 on 2025-09-13 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryDevice',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('device_type', models.CharField(choices=[('RADIO', 'Radio Equipment'), ('COMPUTER', 'Computer System'), ('PHONE', 'Secure Phone'), ('TABLET', 'Tablet Device'), ('SENSOR', 'Sensor Equipment'), ('VEHICLE', 'Vehicle System'), ('WEAPON', 'Weapon System'), ('OTHER', 'Other Equipment')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('REPAIR', 'Needs Repair'), ('RETIRED', 'Retired'), ('LOST', 'Lost/Stolen')], default='ACTIVE', max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Military Device',
                'verbose_name_plural': 'Military Devices',
                'db_table': 'military_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('mission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mission_name', models.CharField(max_length=200)),
                ('mission_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='UNCLASSIFIED', max_length=15)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PLANNING', max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('objectives', models.TextField()),
                ('resources_required', models.TextField()),
                ('risk_assessment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandMilitaryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military_id', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(choices=[('COMMAND', 'Command Authority'), ('OPERATIONS', 'Operations Officer'), ('INTELLIGENCE', 'Intelligence Officer'), ('COMMUNICATIONS', 'Communications Specialist'), ('FIELD', 'Field Personnel'), ('EMERGENCY', 'Emergency Override')], default='FIELD', max_length=20)),
                ('branch', models.CharField(choices=[('ARMY', 'Army'), ('NAVY', 'Navy'), ('AIR_FORCE', 'Air Force'), ('MARINES', 'Marines'), ('COAST_GUARD', 'Coast Guard'), ('SPACE_FORCE', 'Space Force')], default='ARMY', max_length=20)),
                ('clearance_level', models.CharField(choices=[('TOP_SECRET', 'Top Secret'), ('SECRET', 'Secret'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted'), ('UNCLASSIFIED', 'Unclassified')], default='UNCLASSIFIED', max_length=20)),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('deployment_status', models.CharField(default='ACTIVE', max_length=50)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requires_2fa', models.BooleanField(default=False)),
                ('is_active_duty', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Command Military User',
                'verbose_name_plural': 'Command Military Users',
                'db_table': 'command_military_users',
            },
        ),
        migrations.CreateModel(
            name='CommandSecurityEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('ACCESS_GRANTED', 'Access Granted'), ('ACCESS_DENIED', 'Access Denied'), ('SECURITY_VIOLATION', 'Security Violation'), ('PASSWORD_CHANGE', 'Password Change'), ('2FA_SUCCESS', '2FA Success'), ('2FA_FAILED', '2FA Failed')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('module_accessed', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_resolved_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Command Security Event',
                'verbose_name_plural': 'Command Security Events',
                'db_table': 'command_security_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MilitaryMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('NORMAL', 'Normal'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent'), ('FLASH', 'Flash Override')], default='NORMAL', max_length=10)),
                ('classification', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='UNCLASSIFIED', max_length=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(related_name='received_military_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_military_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Military Message',
                'verbose_name_plural': 'Military Messages',
                'db_table': 'military_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('service_number', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('enlistment_date', models.DateField()),
                ('current_assignment', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Duty'), ('DEPLOYED', 'Deployed'), ('RESERVE', 'Reserve'), ('TRAINING', 'Training'), ('MEDICAL', 'Medical Leave'), ('DISCHARGED', 'Discharged')], default='ACTIVE', max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('medical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('military_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='army1.commandmilitaryuser')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'db_table': 'command_personnel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OperationalLedger',
            fields=[
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUDGET_ALLOCATION', 'Budget Allocation'), ('EQUIPMENT_PURCHASE', 'Equipment Purchase'), ('PERSONNEL_PAYMENT', 'Personnel Payment'), ('MAINTENANCE_COST', 'Maintenance Cost'), ('FUEL_EXPENSE', 'Fuel Expense'), ('TRAINING_COST', 'Training Cost'), ('OTHER', 'Other Expense')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cost_center', models.CharField(max_length=50)),
                ('transaction_date', models.DateField()),
                ('fiscal_year', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army1.militarydevice')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army1.mission')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_transactions', to='army1.personnel')),
            ],
            options={
                'verbose_name': 'Operational Ledger Entry',
                'verbose_name_plural': 'Operational Ledger',
                'db_table': 'operational_ledger',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='assigned_personnel',
            field=models.ManyToManyField(related_name='assigned_missions', to='army1.personnel'),
        ),
        migrations.AddField(
            model_name='mission',
            name='commander',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commanded_missions', to='army1.personnel'),
        ),
        migrations.AddField(
            model_name='militarydevice',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army1.personnel'),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('SECURITY', 'Security'), ('NETWORK', 'Network'), ('AUTH', 'Authentication'), ('APPLICATION', 'Application'), ('DATABASE', 'Database')], default='SYSTEM', max_length=15)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'command_system_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['level', 'category', 'timestamp'], name='command_sys_level_702697_idx'), models.Index(fields=['timestamp'], name='command_sys_timesta_d1a2a1_idx')],
            },
        ),
    ]
