# Generated by Django 5.2.6 on 2025-09-13 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Conversation name/title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Conversation description')),
                ('conversation_type', models.CharField(choices=[('DIRECT', 'Direct Message'), ('GROUP', 'Group Conversation'), ('CHANNEL', 'Channel/Broadcast'), ('EMERGENCY', 'Emergency Channel'), ('COMMAND', 'Command Channel')], default='DIRECT', max_length=15)),
                ('classification_level', models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='UNCLASSIFIED', max_length=15)),
                ('required_clearance', models.CharField(blank=True, help_text='Minimum clearance required', max_length=20)),
                ('encryption_key_id', models.CharField(help_text='Conversation encryption key identifier', max_length=100)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('auto_delete_after', models.IntegerField(blank=True, help_text='Auto-delete messages after N days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('VOICE', 'Voice Message'), ('VIDEO', 'Video Message'), ('FILE', 'File Attachment'), ('IMAGE', 'Image'), ('LOCATION', 'Location Share'), ('COMMAND', 'Command Message'), ('ALERT', 'Alert/Notification')], default='TEXT', max_length=10)),
                ('content_encrypted', models.TextField(help_text='Encrypted message content')),
                ('content_hash', models.CharField(help_text='SHA-256 hash of original content', max_length=64)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_count', models.IntegerField(default=0)),
                ('thread_id', models.UUIDField(blank=True, help_text='Thread identifier for message grouping', null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachment_count', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Message expiration time', null=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('is_offline_message', models.BooleanField(default=False)),
                ('offline_created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('ARCHIVE', 'Archive'), ('OTHER', 'Other')], max_length=10)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_path_encrypted', models.TextField(help_text='Encrypted file path')),
                ('encryption_key_id', models.CharField(max_length=100)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of original file', max_length=64)),
                ('virus_scan_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan Error')], default='PENDING', max_length=10)),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('retry_after', models.DateTimeField(blank=True, null=True)),
                ('is_offline_delivery', models.BooleanField(default=False)),
                ('offline_queued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message Delivery',
                'verbose_name_plural': 'Message Deliveries',
                'db_table': 'message_deliveries',
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('LIKE', '👍'), ('DISLIKE', '👎'), ('ACKNOWLEDGE', '✅'), ('UNDERSTOOD', '👌'), ('URGENT', '🚨'), ('QUESTION', '❓'), ('IMPORTANT', '⚠️'), ('COMPLETED', '✔️')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'db_table': 'message_reactions',
            },
        ),
    ]
